Feature/adding additional props
stackai/react-stackai pull request #6
Opened 2023-12-04 19:14 UTC by houmland

## Description

Changes:
- Added optional props to give specific width and height to the chatbot. 
- Added optional prop to make the chatbot relative so the user can place it wherever she likes.
- Fixed bug when chatbot is 'always open' - sizes where 90x90 px. 

## Changes Made

Changes:
- Added optional props to give specific width and height to the chatbot. 
- Added optional prop to make the chatbot relative so the user can place it wherever she likes.
- Fixed bug when chatbot is 'always open' - sizes where 90x90 px. 
## Screenshots (if applicable)

## Checklist

- [x] I have tested these changes locally and they work as expected.
- [ ] I have updated the README if necessary.

## Related Issues

## Deployment Notes

2023-12-05 20:31 UTC, sanchezfdezjavier requested changes

2023-12-08 16:45 UTC, houmland commented on src/Stack.tsx
> +        position: fixed? 'fixed' : 'relative',
Let me check - I did not know there was a default 'block' when position was not defined.

2023-12-08 17:00 UTC, houmland commented on src/Stack.tsx
> +  height = '38.5rem', // Default height value
<img width="238" alt="image" src="https://github.com/stackai/react-stackai/assets/43064045/35a887a9-35f5-4d37-883a-beb94a759c10">

height crops, width get adjusted. I'll fix this.

2023-12-19 14:23 UTC, sanchezfdezjavier approved these changes

2023-12-20 09:01 UTC, merged